export const Style = {
    flexColCenterCenter: `flex flex-col justify-center items-center `,
    flexColStartCenter: `flex flex-col justify-start items-center `,
    flexColBetweenCenter: `flex flex-col space-between items-center `,
    flexColStartEvenly: `flex flex-col justify-start items-evenly `,
    flexColEvenlyStart: `flex flex-col justify-evenly items-start `,
    flexRowCenterCenter: `flex flex-row justify-center items-center `,
    flexRowStartCenter: `flex flex-row justify-start items-center `,
    sizeFull: `h-full w-full`,
    textColorPrimary: `text-red-500`,
    bgPrimary: `bg-red-500`,
    fillPrimary: `fill-red-500`,
    fillPrimaryLight: `fill-red-400`,
    borderPrimary: `border-red-500`,
    textColorSecondary: `text-gray-300 `,
    iconBg: `h-10 w-10 flex flex-col items-center justify-center bg-zinc-700 rounded-full bg-opacity-50 mx-2`,
    iconBgBig: `h-14 w-14 flex flex-col items-center justify-center bg-zinc-800 rounded-full bg-opacity-50 mx-2`,
    pageContainer: `px-5 md:px-10 lg:px-20 py-28 lg:py-34`,
};
